import Dexie, { type Table } from "dexie";
import type { PM3DumpJson } from "@/components/panels/CardMemoryMap";
import type { StoredCard, StoredKey } from "@/components/panels/library/types";
import type { CachedAssetKind } from "@/features/key-cache/types";

/**
 * A captured/loaded card dump. This merges what used to be two separate stores —
 * the dump data (localStorage `pm3-dumps`) and its favorite/notes metadata
 * (localStorage `pm3-library-dump-meta`) — into one row.
 */
export interface DumpRecord {
  id: string;
  name: string;
  data: PM3DumpJson;
  /** Normalized UID, indexed so a card's dumps can be found by UID. */
  uid: string;
  cachedAt: number;
  favorite: boolean;
  notes: string;
  updatedAt: number;
}

/** Library keys and cards keep their existing shapes — now rows, not a JSON blob. */
export type KeyRecord = StoredKey;
export type CardRecord = StoredCard;

/** A cached file (key dictionary, dump, script, …) uploaded or generated by pm3. */
export interface AssetRecord {
  id: string;
  name: string;
  relativePath?: string;
  kind: CachedAssetKind;
  size: number;
  base64: string;
  updatedAt: number;
}

/**
 * The single IndexedDB database behind the whole vault. Replaces the five
 * independent localStorage stores (dumps, dump-meta, keys, cards, file cache)
 * the app used to juggle. One DB, one schema, queried reactively via Dexie.
 */
export class VaultDatabase extends Dexie {
  dumps!: Table<DumpRecord, string>;
  keys!: Table<KeyRecord, string>;
  cards!: Table<CardRecord, string>;
  assets!: Table<AssetRecord, string>;

  constructor() {
    super("pm3-vault");
    this.version(1).stores({
      dumps: "id, uid, cachedAt",
      keys: "id, uidFilter, kind",
      cards: "id, uid",
      assets: "id, kind, updatedAt",
    });
  }
}

export const db = new VaultDatabase();
