import Dexie, { type Table } from "dexie";
import type { PM3DumpJson } from "@/components/panels/CardMemoryMap";
import type { StoredCard, StoredKey } from "@/components/panels/library/types";
import type { CachedAssetKind } from "@/features/key-cache/types";

export type OperationKind = "attack" | "write" | "erase" | "read" | "device" | "command";
export type OperationStatus = "running" | "succeeded" | "warning" | "failed" | "cancelled";

export type OperationCheckState = "ok" | "warning" | "error" | "info" | "skipped";
export interface OperationCheckRecord {
  id: string;
  label: string;
  state: OperationCheckState;
  detail: string;
  blocking: boolean;
}

/** Durable, transport-neutral record of work performed by the PM3 client. */
export interface OperationRecord {
  id: string;
  kind: OperationKind;
  command: string;
  origin: string;
  status: OperationStatus;
  queuedAt: number;
  startedAt: number | null;
  endedAt: number | null;
  durationMs: number | null;
  targetUid?: string;
  targetType?: string;
  transport?: string;
  phase?: string;
  progress?: number;
  summary?: string;
  recovery?: {
    code: string;
    message: string;
    action: string;
    retryable: boolean;
  };
  outputTail: string[];
  updatedAt: number;
  workflow?:
    | "type2-read"
    | "type2-write"
    | "type2-clear"
    | "type2-zero"
    | "mifare-batch"
    | "mifare-verified-restore"
    | "lf-verified-write"
    | "magic-uid-write"
    | "magic-block0-write"
    | "magic-dump-restore";
  profile?: string;
  method?: string;
  checks?: OperationCheckRecord[];
  backupId?: string;
  verified?: boolean;
  affectedPages?: number[];
}

/** Binary before-image retained in IndexedDB for recovery without OS paths. */
export interface BackupRecord {
  id: string;
  name: string;
  kind: "type2" | "mifare";
  uid?: string;
  operationId?: string;
  mimeType: string;
  base64: string;
  size: number;
  createdAt: number;
}

/**
 * A captured/loaded card dump. This merges what used to be two separate stores —
 * the dump data (localStorage `pm3-dumps`) and its favorite/notes metadata
 * (localStorage `pm3-library-dump-meta`) — into one row.
 */
export interface DumpRecord {
  id: string;
  name: string;
  data: PM3DumpJson;
  /** Normalized UID, indexed so a card's dumps can be found by UID. */
  uid: string;
  cachedAt: number;
  favorite: boolean;
  notes: string;
  updatedAt: number;
}

/** Library keys and cards keep their existing shapes — now rows, not a JSON blob. */
export type KeyRecord = StoredKey;
export type CardRecord = StoredCard;

/** LF technologies we can persist a decoded credential for. */
export type LfTech =
  | "hid"
  | "em410x"
  | "indala"
  | "awid"
  | "ioprox"
  | "fdxb"
  | "paradox"
  | "keri"
  | "pyramid"
  | "raw";

/**
 * A decoded LF credential (e.g. an HID Prox read). LF reads print no file, so
 * unlike HF dumps they used to vanish into the terminal; this row is what gives
 * them a home in the vault and lets the write/clone UI reload them later.
 */
export interface LfCardRecord {
  id: string;
  name: string;
  /** Normalized UID/ident, indexed so an LF card can be paired with its HF twin. */
  uid: string;
  tech: LfTech;
  /** Wiegand format for prox cards, e.g. "H10301". */
  format?: string;
  facilityCode?: number;
  cardNumber?: number;
  /** Raw hex (wiegand raw for HID, tag id for EM410x). */
  raw?: string;
  /** Format-specific decoded values, kept registry-driven for future formats. */
  fields?: Record<string, string | number>;
  /** Carrier chip from `lf t55xx detect`, e.g. "T55x7". */
  chip?: string;
  /** T55xx config block0 hex. */
  config?: string;
  /** True once a `lf t55xx detect` confirmed a writable T5577/T5555 carrier. */
  writable?: boolean;
  cachedAt: number;
  favorite: boolean;
  notes: string;
  updatedAt: number;
}

/** A cached file (key dictionary, dump, script, …) uploaded or generated by pm3. */
export interface AssetRecord {
  id: string;
  name: string;
  relativePath?: string;
  kind: CachedAssetKind;
  size: number;
  base64: string;
  updatedAt: number;
}

// ---------------------------------------------------------------------------
// Virtual cards
// ---------------------------------------------------------------------------

/**
 * What the physical thing actually is. A UID says nothing about whether you are
 * holding a badge, a keyfob or a sticker, so the user states it once here and
 * every list can show it.
 */
export type VirtualCardForm =
  | "card"
  | "fob"
  | "tag"
  | "sticker"
  | "wristband"
  | "implant"
  | "ring"
  | "phone"
  | "other";

/** Why this item is in the library — the issued thing, or something we wrote. */
export type VirtualCardRole = "original" | "clone" | "blank" | "test";

/**
 * A "virtual card": one real-world credential, assembled from the rows that are
 * scattered across the technology-shaped tables. A dual-frequency badge is a
 * single virtual card whose members are an HF card row, an LF credential row,
 * and the dumps/keys recovered from either side — the other tables stay flat and
 * protocol-specific, while this row is the thing the user actually recognizes.
 */
export interface VirtualCardRecord {
  id: string;
  /** Nickname, e.g. "Office badge". */
  name: string;
  form: VirtualCardForm;
  role: VirtualCardRole;
  /** Who issued it / where it is used, e.g. "UNBC", "Gym". */
  issuer?: string;
  /** Palette key for the colour dot shown in lists (see virtualCards.ts). */
  color?: string;
  /** Free-form labels for grouping, e.g. ["work", "door access"]. */
  tags: string[];
  favorite: boolean;
  notes: string;
  createdAt: number;
  updatedAt: number;
}

/** The vault tables a virtual card can draw members from. */
export type VirtualCardMemberKind = "card" | "lfCard" | "dump" | "key" | "asset";

/**
 * A membership edge between a virtual card and one row in another table. Kept
 * as its own table rather than a column on each record so linking never has to
 * rewrite — or migrate — the protocol-specific rows, and so one dump or key can
 * belong to more than one virtual card (an original and its clone).
 */
export interface VirtualCardMemberRecord {
  /** Deterministic `<virtualCardId>:<kind>:<refId>` so re-linking is a no-op. */
  id: string;
  virtualCardId: string;
  kind: VirtualCardMemberKind;
  refId: string;
  addedAt: number;
}

/**
 * The single IndexedDB database behind the whole vault. Replaces the five
 * independent localStorage stores (dumps, dump-meta, keys, cards, file cache)
 * the app used to juggle. One DB, one schema, queried reactively via Dexie.
 */
export class VaultDatabase extends Dexie {
  dumps!: Table<DumpRecord, string>;
  keys!: Table<KeyRecord, string>;
  cards!: Table<CardRecord, string>;
  assets!: Table<AssetRecord, string>;
  lfCards!: Table<LfCardRecord, string>;
  operations!: Table<OperationRecord, string>;
  backups!: Table<BackupRecord, string>;
  virtualCards!: Table<VirtualCardRecord, string>;
  virtualCardMembers!: Table<VirtualCardMemberRecord, string>;

  constructor() {
    super("pm3-vault");
    this.version(1).stores({
      dumps: "id, uid, cachedAt",
      keys: "id, uidFilter, kind",
      cards: "id, uid",
      assets: "id, kind, updatedAt",
    });
    // v2 adds the LF credential store. Dexie migrates existing databases in
    // place; the four original tables keep their data untouched.
    this.version(2).stores({
      dumps: "id, uid, cachedAt",
      keys: "id, uidFilter, kind",
      cards: "id, uid",
      assets: "id, kind, updatedAt",
      lfCards: "id, uid, updatedAt",
    });
    // v3 adds an append/update audit surface for commands and guided workflows.
    this.version(3).stores({
      dumps: "id, uid, cachedAt",
      keys: "id, uidFilter, kind",
      cards: "id, uid",
      assets: "id, kind, updatedAt",
      lfCards: "id, uid, updatedAt",
      operations: "id, kind, status, startedAt, endedAt, targetUid, updatedAt",
    });
    // v4 stores browser-native binary before-images for safe destructive workflows.
    this.version(4).stores({
      dumps: "id, uid, cachedAt",
      keys: "id, uidFilter, kind",
      cards: "id, uid",
      assets: "id, kind, updatedAt",
      lfCards: "id, uid, updatedAt",
      operations: "id, kind, status, startedAt, endedAt, targetUid, updatedAt",
      backups: "id, kind, uid, operationId, createdAt",
    });
    // v5 adds the virtual-card layer: user-named real-world credentials that
    // group the HF/LF rows, dumps and keys belonging to one physical card.
    this.version(5).stores({
      dumps: "id, uid, cachedAt",
      keys: "id, uidFilter, kind",
      cards: "id, uid",
      assets: "id, kind, updatedAt",
      lfCards: "id, uid, updatedAt",
      operations: "id, kind, status, startedAt, endedAt, targetUid, updatedAt",
      backups: "id, kind, uid, operationId, createdAt",
      virtualCards: "id, name, form, updatedAt",
      virtualCardMembers: "id, virtualCardId, kind, refId, [virtualCardId+kind], [kind+refId]",
    });
  }
}

export const db = new VaultDatabase();
